[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".env.local"]

# Redirections pour SPA
[[redirects]]
  from = "/catalogue-v2.html"
  to = "/catalogue"
  status = 301

# Redirection SPA désactivée pour Next.js

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache optimisé pour assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js configuration
[env]
  NEXT_RUNTIME = "nodejs18.x"